monzo/gocassa

- interfaces.go
- keyspace.go
- table.go
- Add optional `TableOptions` to the table constructors which takes a `gocassa.TableOptions`
- Remove crappy `...WithName` constructors
- `TableName` can be specified in the `TableOptions` when constructing a table
> Table options

- modifiers.go
Allows you to SET individual fields in `map[string]time.Time` columns
> Allow MapSetFields with time.Time values

- mock_test.go
- op.go
The bug was that `Noop()` returned an `op` so when using a mock keyspace it would panic because the Add method on the `op` struct type cast the `Op` to an `op` but it was actually a `mockOp`.
> Add noop type to get around interface issues.

- filter.go
- gocql_backend.go
- interfaces.go
- mock.go
- multiop.go
- op.go
- query_test.go
- table.go
Previously, `Op` wasn't really a "useable" interface since there were internal type assertions in many places. This PR makes it into a "proper" `Op` for which there can be many implementations.
This also includes a change to make the tests more resilient on CI. FU Travis :rage:.
> Refactor Op

- bucket.go
- filter.go
- flakeseries_table.go
- flakeseries_table_test.go
- interfaces.go
- mock.go
- multiflakeseries_table.go
- multiflakeseries_table_test.go
- multitimeseries_table.go
- timeseries_table.go
- timeseries_table_test.go
This adds support for the "bucket iteration" pattern, where a client queries each bucket successively until it has enough results. The interface supports forward and backward iteration, with an interface similar to those found in the [Go stdlib](https://golang.org/pkg/container/list/#Element).
```go
type Buckets interface {
Filter() Filter
Bucket() time.Time
Next() Buckets
Prev() Buckets
}
```
Of course, this pattern should be used cautiously – it requires enough nodes are available to achieve the desired consistency level for _every_ bucket iterated over.
The internal code paths like `List` have been refactored to use bucket iteration under the covers, though these use the buckets to construct an `IN` query rather than sequentially iterating in the client.
> Bucket iteration support

- .travis.yml
- keyspace.go
Returns an error rather than panicing if there is no `QueryExecutor` available. This "fixes" the case where we use a mock during testing, which doesn't have a query executor, and therefore panics.
> Return error if no query executor is available

- mock.go
- mock_test.go
Before, when you wanted a mock multi-op to RunAtomically, the non-mock
multiOp would try to use the always-nil QueryExecutor and would panic.
This introduces a mocked multi-op to, like the mockOp, just use Run in
place of RunAtomically.
> Fixed panic in mock multi-Op RunAtomically()

- .travis.yml
- mock.go
The reflect code in gocassa does not treat maps in any special way when
converting structs to maps for internal use. This means that if your
struct has a map[string]string, it will remain a map[string]string.
However when using MapSetFields the requested changes are in a
map[string]interface{} so we need to ensure that when we copy from
MapSetFields map[string]interface{} to the record value that we don't
assume the map in the record is also a map[string]interface{}, but could
be, for example, a map[string]string.
Note that my knowledge of gocassa is limited so do verify I'm fixing this in the right place. This change does fix it for my code (I had a map[string]string that I did a mutation on).
> support maps that are not map[string]interface{}

- .travis.yml
- multiop.go
This is a couple of very small optimisations to the code of `multiOp`, which both benefit performance and make testing work a little better.
Currently, `multiOp` and `RunAtomically()` don't play well together, because `mockOp` does not support `QueryExecutor()`, which `multiOp` tries to use. While this doesn't really "fix" the situation, it makes it a bit less likely to occur by "flattening out" `multiOp`s more aggressively, which can result in its `RunAtomically` method never being executed.
This is a bit gross, but I don't have the time right now to embark on a full-scale refactor of how mocking works (which is what's really needed here). 😷
> multiOp enhacements

- interfaces.go
- keyspace.go
- multikey_timeseries_table.go
- multikey_timeseries_table_test.go
- query_test.go
This PR adds a new recipe which is a combination of the timeseries and MultimapMkTable tables, this recipe lets you create a timeseries which uses composite keys.
> Add new multikey timeseries table

- mock.go
This pull request fixes a bug in the method `MockTable.WithOptions`.
The Gocassa `MockTable` implementation uses a `map` to store the table's `rows`. In Go, [`map` operations are not safe for concurrent use](https://golang.org/doc/faq#atomic_maps), so `MapTable` stores a `sync.RWMutex`, named `mtx` to stop concurrent access to `rows`.
`MockTable` implements a method, `WithOptions`, which returns a *new* `MockTable`, with the supplied options. When this new `MockTable` is constructed, `rows` is passed over. Because `rows` is a `map`, it is passed by reference. Both the old and new `MockTable`s read and write data from the *same* `map`.
Previously, `WithOptions` returned a new `MockTable` with a *new* mutex. There would be two `MockTables` reading and writing to the same `map`, which were …
> Persist mutex over MockTable.WithOptions

- keyspace.go
- mock_test.go
I'm not sure why the bucket should be the last key, but [this](https://github.com/monzo/gocassa/blob/master/mock.go#L416) is checking for it.
This adds `bucket` as the last key when creating a `MultiKeyTimeseries` table and some mock tests.
> Fixes MultikeyTimeseries mock table

- keyspace.go
In 0dffc2c5e617a2f58365ae90fcb800a331d67d7f this was updated from selecting from `system.schema_columnfamilies` to selecting from `columnfamily_name`, and the field selected changed from a column family name to a table name.
This indexes the result map with the new selection, allowing the tests to run.
> 🔧refer to result set by selection alias

- .travis.yml
- options.go
Add a very basic way to propagate `context` by adding to the `Options` which means the interface is unchanged. This allows a user to propagate a context (ie a request context with a trace ID) through to the `QueryExecutor` which may be custom. 
Usage:
```
someTable.Read(id, result).WithOptions(Options{Context: ctx}).Run()
```
I've also bumped the cassandra version used in the tests, as this was no longer present on the download server 😐
> Add context to Options, allowing per query contexts

- .travis.yml
- op.go
- table.go
I went on a 🐛 hunt this evening trying to determine why we're using so many Cassandra prepared statements. 
Currently, GoCassa is iterating over the fields of UPDATE/INSERT statement maps. This means we get a non-deterministic ordering of field names when the CQL statement is generated, resulting in the same gocassa operation yielding different generated statements. 
For example, the first time you might get
```
UPDATE test_keyspace.test_table SET val1 = ?, val2 = ?, val3 = ?
```
And a subsequent time you might get
```
UPDATE test_keyspace.test_table SET val2 = ?, val3 = ?, val1 = ?
```
and so on.
This PR fixes by iterating over the map in a deterministic order by field name.
Now you might ask how this relates to prepared statements. [GoCQL](http://github.com/monzo/gocql) uses prepared …
> Iterate through the field map in sorted order 🐛

- table.go
Along the lines of https://github.com/monzo/gocassa/pull/35, this PR modifies the order in which fields are stored to ensure they are sorted.
This list of fields is used to generate the `SELECT` statement in GoCassa. Since it's populated from a map, the ordering of field names is not consistent. 
This 🐛 was a bit more tricky to track down because the list of fields is set in stone when you define the GoCassa table. This means if you define the table as a constant, within one running instance of your program, you'll have consistent ordering of fields no matter how many times you run the query. However, across different instances of the same program, the ordering will be varied.
For example, `myapplication-abcd1` may be consistently requesting
```
SELECT field1, field2, field3, field4 FROM …
```
> Order field names to get consistent select statements 🐞

- op.go
- table.go
Right now, we're generating statements with the TTL not bound. For some of our services, we generated TTLs from now to a fixed point in the future. This means our prepared statement cache keeps growing as the TTLs change relative to time.
From Cassandra 2.0, [you can bind the TTL](https://groups.google.com/a/lists.datastax.com/forum/#!topic/java-driver-user/V5c6GCl-ovk) as an argument just like anything else, and thus we should.
With this PR, we go from doing:
```
UPDATE foospace.blah USING TTL 5122948 SET val1 = ?, val2 = ?, val3 = ?
INSERT INTO foospace.blah (val1, val2, val3) VALUES (?, ?, ?) USING TTL 5122948 
```
to
```
UPDATE foospace.blah USING TTL ? SET val1 = ?, val2 = ?, val3 = ?
INSERT INTO foospace.blah (val1, val2, val3) VALUES (?, ?, ?) USING TTL ? 
```
> Ensure we bind the TTL within our statements 🕰

- mock.go
- mock_test.go
This PR adds an implementation of `modifierMapSetField` in the mock so we can use `gocassa.MapSetField` in our tests.
> Add modifierMapSetField handling in mock

- errors.go
- gocql_backend.go
- interfaces.go
- mock.go
- mock_test.go
- multiop.go
- op.go
- table_test.go
We need to start encouraging the passing of context to gocassa functions wherever possible - this will allow us to use jaeger tracing to track what we're sending to cassandra and how long it takes. Adding this sugar will hopefully make this easier for engineers to change their habits.
> Add RunWithContext and RunAtomicallyWithContext

- README.md
It would be good to explicitly mention here that running the tests
requires the cassandra service to be running locally.
> update readme with instructions for running the tests

- mock.go
- mock_test.go
Currently, we only check whether or not the key is present, we also need
to check if the value is an empty string. As far as I understand, it is
safe to write zero values for other types like int, time etc. in the
primary key, and writes only fail for empty strings.
This is a hack, and I couldn't figure out any other way of solving this.
I really wanted to fix this because real C* behavior would be to return
an error here, while unit tests with mocked keyspaces would happily
pass.
> make sure that mock returns an error for an empty primary key

- mock.go
- mock_test.go
The behaviour with `Op`'s in normal usage is to merge any `Options` specified
in `WithOptions` with the `Op`'s existing `Options`. This was not being
followed in `mockOp`. This commit fixes this by making sure we always merge
with any existing `Options`, thus preventing the mocked `WithOptions`
unsetting any `Options` already set.
This commit also adds a test case to cover this.
> Merge existing options when mocking WithOptions

- CHANGELOG.md
- doc.go
- gocql_backend.go
- interfaces.go
- mock.go
- mock_test.go
- scanner.go
- scanner_test.go
Previously, we were treating a failed loop of the iterator as a `RowNotFound` error. This fixes that by actually looking at the error and acting appropriately. 
The `Scannable` interface has had to be added to so it's basically a `gocql.Scanner` which is fine as the two now intermingle and we can add appropriate testing in our mocks.
> 😨 gocql errors should not always be treated as RowNotFound errors

- CHANGELOG.md
- README.md
- relation.go
- relation_test.go
We found a case where a mock keyspace in tests would panic when there was a blob column in the primary key of a table while writing tests for #31873
`panic: runtime error: comparing uncomparable type []uint8`
The line panicing seemed to be this one:
https://github.com/monzo/gocassa/blob/ef231cad77826485d5858060ccee5e4c89cd4d36/relation.go#L46
This seems to be a limitation in gocassa as it attempts to compare two `[]byte` variables wrapped in `{}interface`, which Go doesn't allow. This ends up panicing the runtime.
The solution proposed and implemented in this PR is based on the fact that go `[]byte` slices can be cast to `string` without changing the bytes in the slice, even if that results in an invalid utf-8 sequence (go deals with this at runtime when parsing the string for rendering). …
> Add support for blob types in primary key

- relation.go
- relation_test.go
If you passed in a type which was a proxy for `string`, it'd still fail the type conversion test. This makes sure we can handle it
> 🆎 Support proxy types in mock implementation for comparison

- .travis.yml
Fixes the tests so they actually run on Travis (the Oracle package gives us nothing fancy in tests and is a pain to install.
Also enables Go 1.13
> 🤞 Use OpenJDK for Travis tests and include Go 1.13

- errors.go
- interfaces.go
- mock.go
- mock_test.go
- multiop.go
- op.go
- query_test.go
The name RunAtomically is misleading - it doesn't give atomicity in the
"traditional" sense. It doesn't provide isolation (so other readers may
observe inconsistent state), and it doesn't provide Read-Your-Writes
consistency. That is to say, assuming the following three operations are
the _only_ operations issued on the database:
* A write with RunAtomically (which returns an error)
* A read of the written row
* A second read of the written row
In some failure cases, both reads may return different values (in
particular, the first read can observe the old value and the second read
the new value), even if all operations were to be performed at QUORUM
consistency
The name RunAtomically is therefore an attractive nuisance. The name
RunLoggedBatch - which takes its name from the underlying …
> Rename RunAtomically to RunLoggedBatch

- gocql_backend.go
Currently the context passed in the options of ExecuteWithOptions and QueryWithOptions is not actually propagated into gocql. This PR fixes this.
> Propagate context into gocql backend

- .travis.yml
- table.go
- table_test.go
This is protection [against a nasty Cassandra bug](https://issues.apache.org/jira/browse/CASSANDRA-11805) where UPSERTing a row with all the non-partition/clustering column keys as 'null' causes the entire row to be deleted. This is undesirable behaviour and we should rather use an INSERT to retain the original data
> Use an INSERT rather than an UPSERT when only touching partition/clustering columns

- README.md
Keys are `string`, not `Sale`.
> Fixed typo in example from README

- bench_test.go
- connection.go
- errors.go
- generate.go
- keyspace.go
- mock.go
- multiop.go
- op.go
- options.go
- relation.go
- scanner.go
- scanner_test.go
- statement.go
- statement_test.go
- table.go
This PR refactors some of the internals of gocassa to centralise the CQL building logic around the Statement interface. Previously, it was contained within the mismash of the `Op` set of objects.
This PR makes a clean separation, the Op is responsible for building the commands up, it then hands over the reins to the Statement which is responsible for generating the query.
As a bonus, we now have great tests around generating a CQL query as that's much more self-contained. There were already suitable integration tests which i've leaned on to make sure we don't have other regressions. 
This PR is quite large so it's advised to go commit by commit 🙏
> Refactor generating CQL to Statement 🗣️

- op.go
- statement.go
- statement_test.go
This PR adds constructors for our different Statement types (as well as primitive validation logic). It also includes plumbing of the Keys data type from the table info to provide information on the table partition/clustering keys.
> Add Partition/Clustering Key and Constructors

- reflect/cache.go
- reflect/reflect.go
- reflect/reflect_test.go
- scanner.go
- scanner_test.go
This PR makes a few tweaks to improve the performance of decoding into a slice
- When decoding a slice, a bug meant we were doing double allocations of slice values and then throwing the second set away (because they were never used)
- When we initialize/create a struct element, it comes pre-allocated with the zero values of elements. We can use those allocations rather than allocate ourselves again. This also saves some double allocations and gives as a bonus of not having to re-iterate and set the pointers (so instead of an intermediate variable to decode from struct element to intermediate variable to struct element), we just pass the direct struct element to be decoded into
This code is already [well covered with tests](https://github.com/monzo/gocassa/blob/master/scanner_test.go) so …
> Make slice decoding more performant 💨

- mock.go
`(*MockTable).WithOptions` is [called frequently by the table helpers](https://github.com/monzo/gocassa/blob/1abfd4f7a2d9efd72c6a618226111fbe4ce5fc9b/multimap_multikey_table.go#L63-L70)
Each call to `WithOptions` instantiates a new instance of `*MockTable* copying all struct members from the receiver table **including a `sync.RWMutex**. Copying a `sync.RWMutex` creates a **new** mutex:
```
a := &thing{sync.Mutex{}}
b := &thing{a.Mutex}
a.Lock()
fmt.Println("locked a")
b.Lock()
fmt.Println("locked b")
```
This meant that the mutex was mostly not working which was causing transient test failures in CI.
This PR replaces the `sync.Mutex` on `MockTable` with a `*sync.Mutex` to ensure we're always locking the same mutex
> Use a pointer to the mock table mutex

- mock.go
- mock_test.go
- scanner.go
For implementations which use a strict allowlist of Unmarshalers, it's useful to have this type public so we can test against it and put it in the allow list
> Make IgnoreFieldType public so we can see if that's where we're unmarshaling

- scanner.go
- scanner_test.go
- statement.go
- statement_test.go
In services like Keyspaces, it is not permitted to have empty string/blob clustering values. This PR introduces a sentinel value that can stand-in in these cases because applications may wish to have empty values (since Cassandra _does_ allow you to do so)
> Add ability to have sentinel values for Clustering Columns

- .travis.yml
- mock_test.go
- multimap_table_test.go
This PR cleans up the tests which weren't building when we removed MultiRead support for clustering columns in  https://github.com/monzo/gocassa/pull/73
> Remove tests for MultiMap MultiRead which shouldn't still be present

- scanner.go
- scanner_test.go
If we spot an error when decoding from the slice use case, we should return an error upstream. This makes our decoding consistent between the slice and struct use case.
> Read and propagate error from our iterator when decoding into slice

- .github/workflows/actions.yaml
Our integration with TravisCI seems to have expired. This PR migrates the entire testing to GitHub Actions instead.
> Add a GitHub Action for running tests

- interfaces.go
The question "What should the limit value be set to, in order to disable the limit" has been asked of me many times, and I've never had a good answer.
I've seen this set to -1 and 0 in various pieces of code, so decided to find out definitively so took a look through the code. I found the following comment `// limit count, 0 means no limit` in [statments.go](https://github.com/monzo/gocassa/blob/master/statement.go#L31), and further looking [revealed an if statement that returns 0 if limit < 1.](https://github.com/monzo/gocassa/blob/master/statement.go#L155-L157).
Popping a comment above the function should help reduce the uncertainty that people seems to have when using List with no limit.
Please validate the rest of the comment I've added, I'm certainly no cassandra or gocassa expert.
> Add comment for the List functions

- mock.go
- mock_test.go
This is an exact copy of [Matt's original PR](https://github.com/monzo/gocassa/pull/65) (plus a test), that was reverted due to failing unit tests in services. These tests have been fixed and are waiting on this change to be merged.
> Add support for DESC clustering order in the mock.

- .github/workflows/actions.yaml
- statement.go
We don't need to constantly allocate a new time.Time each we evaluate this path, just to get the reflect.Type
> Remove unnecessary allocation around sentinel checks for reflect.Struct

- generate.go
- generate_test.go
You can use custom field types with gocassa if they implement either the `gocql.Marshaler` and `gocql.Unmarshaler` interfaces or the `gocql.UDTMarshaler` and `gocql.UDTUnmarshaler` interfaces. However, Gocassa's generation code (the code that generates a `CREATE IF NOT EXISTS` statement errors if you call them on a table that uses such a type. It errors because it needs to know what C* type should be used and it doesn't know. At Monzo this means that any service that uses fields of type `*decimal.Decimal` or `*decimal.Money` cannot make use of the generator. This PR introduces a new `CQLTyper` to accompany the `Marshaler` and `Unmarshaler` that can be used to allow gocassa to obtain this information.
> Add support for custom types in generator

- mock.go
- mock_test.go
Currently, if you add a `gocassa.Noop()` to an existing chain of mock operations we throw a panic `can't Add non-mock ops to mockMultiOp`. This is because the type of an empty `Noop()` is `multiOp`, however without any operations in it this won't do anything. This means we can't mock/test code paths that could have an empty `Noop()`, overly simplified example;
```go
func UpdateItemDescription(item *Item, newDescription string) error {
op := gocassa.Noop()
if item.Description != newDescription {
item.Description = newDescription
op.Add(itemsById.Set(item))
}
return op.Run()
}
```
In this PR, we now check if the length of the multiOp is 0 and if it is continue without panicking.
I've added a test case for this, which before the change to `mock.go` was failing
```
$ go test -run …
```
> Allow empty Noop() to be added to mock op chains
